// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOREdDfuRX4bhrOtRqn8aaqyZZL_FIZRU',
    appId: '1:468505582324:web:35207474c34a3a29189ca1',
    messagingSenderId: '468505582324',
    projectId: 'creditpump-27908',
    authDomain: 'creditpump-27908.firebaseapp.com',
    storageBucket: 'creditpump-27908.firebasestorage.app',
    measurementId: 'G-G328606G8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVOmc9r7HSaJA7xCW0nQrqjek58gWvDmM',
    appId: '1:468505582324:android:f0228684c180b7d4189ca1',
    messagingSenderId: '468505582324',
    projectId: 'creditpump-27908',
    storageBucket: 'creditpump-27908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcN2jBqPOtSfHEgfBqThnC_LSJH4Lz40',
    appId: '1:468505582324:ios:577826eff3539bf7189ca1',
    messagingSenderId: '468505582324',
    projectId: 'creditpump-27908',
    storageBucket: 'creditpump-27908.firebasestorage.app',
    iosBundleId: 'com.example.craditapp',
  );
}
